import {
  IsString,
  IsEnum,
  IsNumber,
  IsNotEmpty,
  IsOptional,
  Min,
  IsBoolean,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { MTOProvider, PaymentChannel, FeeType, MarginType, CorridorStatus } from '@src/common/enums';

/**
 * DTO for webhook-based corridor creation from admin backend
 * Payload is encrypted with server's public key and signed by admin
 */
export class WebhookCreateCorridorDto {
  @ApiProperty({
    description: 'Organization ID (from JWT or webhook header)',
    example: 'uuid',
  })
  @IsString()
  @IsNotEmpty()
  organizationId!: string;

  @ApiProperty({
    description: 'MTO Provider',
    enum: MTOProvider,
  })
  @IsEnum(MTOProvider)
  @IsNotEmpty()
  mto!: MTOProvider;

  @ApiProperty({
    description: 'Country code (2 or 3 letters)',
    example: 'US',
  })
  @IsString()
  @IsNotEmpty()
  country!: string;

  @ApiProperty({
    description: 'Payment channel',
    enum: PaymentChannel,
  })
  @IsEnum(PaymentChannel)
  @IsNotEmpty()
  paymentChannel!: PaymentChannel;

  @ApiProperty({
    description: 'Currency code',
    example: 'USD',
  })
  @IsString()
  @IsNotEmpty()
  currency!: string;

  @ApiProperty({
    description: 'Fee type',
    enum: FeeType,
  })
  @IsEnum(FeeType)
  @IsNotEmpty()
  feeType!: FeeType;

  @ApiProperty({
    description: 'Margin type',
    enum: MarginType,
  })
  @IsEnum(MarginType)
  @IsNotEmpty()
  marginType!: MarginType;

  @ApiProperty({
    description: 'Corridor status',
    enum: CorridorStatus,
    example: CorridorStatus.ACTIVE,
  })
  @IsEnum(CorridorStatus)
  @IsNotEmpty()
  status!: CorridorStatus;

  @ApiProperty({
    description: 'Correlation ID for tracking (generated by admin)',
    example: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsString()
  correlationId?: string;
}

/**
 * Encrypted webhook request wrapper
 */
export class EncryptedWebhookPayloadDto {
  @ApiProperty({
    description: 'Encrypted payload (base64)',
    example: 'base64-encoded-rsa-encrypted-data',
  })
  @IsString()
  @IsNotEmpty()
  encryptedPayload!: string;

  @ApiProperty({
    description: 'Organization ID (plaintext, for routing)',
    example: 'uuid',
  })
  @IsString()
  @IsNotEmpty()
  organizationId!: string;

  @ApiProperty({
    description: 'Correlation ID for tracing',
    example: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsString()
  correlationId?: string;

  @ApiProperty({
    description: 'RSA signature of request body (base64) - from x-webhook-signature header',
    example: 'base64-encoded-signature',
    required: false,
  })
  @IsOptional()
  @IsString()
  signature?: string;
}

/**
 * Webhook response with server signature
 */
export class WebhookResponseDto {
  @ApiProperty({
    description: 'Success status',
    example: true,
  })
  success!: boolean;

  @ApiProperty({
    description: 'Created corridor ID',
    example: 'uuid',
    required: false,
  })
  corridorId?: string;

  @ApiProperty({
    description: 'Error message if failed',
    example: 'Corridor already exists',
    required: false,
  })
  error?: string;

  @ApiProperty({
    description: 'Server signature for response (RSA signed)',
    example: 'base64-encoded-signature',
  })
  signature!: string;

  @ApiProperty({
    description: 'Timestamp of response',
    example: new Date().toISOString(),
  })
  timestamp!: string;

  @ApiProperty({
    description: 'Correlation ID for tracing',
    example: 'uuid',
  })
  correlationId!: string;
}
